# Change these first
owner: isquiexx
repo: bot-upptime

sites:
  - name: Telegram Schedule Bot
    url: https://331d73b4-3f86-4570-a236-81dd568d35e9-00-3nq6ja60euwy6.sisko.replit.dev/health
    expectedStatus: 200
    check: every 5 minutes
    maxResponseTime: 10000

status-website:
  baseUrl: /bot-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Telegram Bot Status
  introTitle: "Мониторинг Telegram бота-расписания"
  introMessage: "Статус работы бота с расписанием пар. Бот работает на Replit и мониторится через GitHub Actions."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/isquiexx/bot-upptime

notifications:
  - type: issue
    message: "🚨 {{site.name}} is down! {{site.url}}"
  - type: issue-open
    message: "⚠️ {{site.name}} is down! {{site.url}}"
  - type: issue-close
    message: "✅ {{site.name}} is back up! {{site.url}}"
